version: '2'
services:
  jenkins:
    image: jenkins
    ports:
     - 8080:8080
    volumes:
     - jenkins-data:/var/jenkins_home
  nexus:
    image: sonatype/nexus
    ports:
     - 8081:8081
    volumes:
     - nexus-data:/sonatype-work
  sonar:
    image: sonarqube
    ports:
     - 9000:9000
    links:
     - postgres
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
     - sonar-data:/opt/sonarqube/extensions
     - sonar-data:/opt/sonarqube/lib/bundled-plugins
  postgres:
    image: postgres
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
    volumes:
     - postgres-data:/var/lib/postgresql
volumes:
  jenkins-data:
    driver: local
  nexus-data:
    driver: local
  sonar-data:
    driver: local
  postgres-data:
    driver: local
 
